; PHP Configuration for Laravel
; Alpine Docker

[PHP]
memory_limit = 256M
max_execution_time = 300
upload_max_filesize = 20M
post_max_size = 20M

[Date]
date.timezone = UTC

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 20000
opcache.revalidate_freq = 0
opcache.validate_timestamps = 0
opcache.save_comments = 1

[session]
session.save_handler = redis
session.save_path = "tcp://redis:6379?weight=1"

[redis]
redis.arrays.autorehash = 0
redis.chunklen = 2
redis.failover_strings = 0
