[program:laravel-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work redis --queue=default,emails --sleep=3 --tries=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/app/storage/logs/supervisor_default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
