[supervisord]
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp
nodaemon=true

[program:laravel-queue-otp]
process_name=%(program_name)s_%(process_num)02d
command=sh /docker/supervisor/queue-worker.sh
autostart=true
autorestart=true
startretries=3
startsecs=5
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/app/storage/logs/supervisor_otp.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3

[program:laravel-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=sh /docker/supervisor/queue-default.sh
autostart=true
autorestart=true
startretries=3
startsecs=5
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/app/storage/logs/supervisor_default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
